In [1]:
import pandas as pd
import numpy as np

In [19]:
# data = pd.read_csv('fortune500.csv', encoding='latin1')
companys = pd.read_csv('Fortune 500 Companies.csv', encoding='ISO-8859-1')

In [20]:
companys.shape

(13940, 16)

In [21]:
companys.columns

Index(['name', 'rank', 'year', 'industry', 'sector', 'headquarters_state',
       'headquarters_city', 'market_value_mil', 'revenue_mil', 'profit_mil',
       'asset_mil', 'employees', 'founder_is_ceo', 'female_ceo',
       'newcomer_to_fortune_500', 'global_500'],
      dtype='object')

In [29]:
sectors = companys.groupby('sector')

In [34]:
# sort all sectors in decreasing order 
sectors.size().sort_values(ascending=False)

sector
Financials                       777
Energy                           547
Retailing                        422
Technology                       393
Health Care                      368
Food, Beverages & Tobacco        223
Wholesalers                      210
Materials                        177
Business Services                169
Transportation                   158
Industrials                      155
Chemicals                        125
Engineering & Construction       112
Household Products               103
Motor Vehicles & Parts           100
Aerospace & Defense               96
Media                             93
Hotels, Restaurants & Leisure     89
Telecommunications                81
Food & Drug Stores                55
Apparel                           47
dtype: int64

In [35]:
# Print 1st company of every sector
sectors.first()

,name,rank,year,industry,headquarters_state,headquarters_city,market_value_mil,revenue_mil,profit_mil,asset_mil,employees,founder_is_ceo,female_ceo,newcomer_to_fortune_500,global_500
sector,,,,,,,,,,,,,,,
Aerospace & Defense,Boeing,27,2015,Aerospace & Defense,IL,Chicago,105032.0,90762.0,5446.0,99198.0,165500.0,no,no,no,yes
Apparel,Nike,106,2015,Apparel,OR,Beaverton,86679.0,27799.0,2693.0,18594.0,56500.0,no,no,no,yes
Business Services,ManpowerGroup,144,2015,Temporary Help,WI,Milwaukee,6746.0,20763.0,428.0,7183.0,26000.0,no,no,no,no
Chemicals,Dow Chemical,48,2015,Chemicals,MI,Midland,55546.0,58167.0,3772.0,68796.0,53216.0,no,no,no,yes
Energy,Exxon Mobil,2,2015,Petroleum Refining,TX,Irving,356549.0,382597.0,32520.0,349493.0,83700.0,no,no,no,yes
Engineering & Construction,Fluor,136,2015,Engineering & Construction,TX,Irving,8427.0,21532.0,511.0,8194.0,37508.0,no,no,no,no
Financials,Berkshire Hathaway,4,2015,Insurance: Property and Casualty (Stock),NE,Omaha,357344.0,194673.0,19872.0,526186.0,316000.0,no,no,no,yes
Food & Drug Stores,CVS Health,10,2015,Food & Drug Stores,RI,Woonsocket,117171.0,139367.0,4644.0,74252.0,177800.0,no,no,no,yes
"Food, Beverages & Tobacco",Archer Daniels Midland,34,2015,Food Production,IL,Chicago,29812.0,81201.0,2248.0,44027.0,33900.0,no,no,no,yes
Health Care,UnitedHealth Group,14,2015,Health Care: Insurance and Managed Care,MN,Minnetonka,112813.0,130474.0,5619.0,86382.0,170000.0,no,no,no,yes
"Hotels, Restaurants & Leisure",McDonald's,110,2015,Food Services,IL,Oak Brook,93651.0,27441.0,4758.0,34281.0,420000.0,no,no,no,yes
Household Products,Procter & Gamble,32,2015,Household and Personal Products,OH,Cincinnati,221280.0,84537.0,11643.0,144266.0,118000.0,no,no,no,yes
Industrials,Caterpillar,54,2015,Construction and Farm Machinery,IL,Peoria,48512.0,55184.0,3695.0,84681.0,114233.0,no,no,no,yes
Materials,International Paper,114,2015,"Packaging, Containers",TN,Memphis,23464.0,26221.0,555.0,28684.0,58000.0,no,no,no,yes
Media,Walt Disney,57,2015,Entertainment,CA,Burbank,178267.0,48813.0,7501.0,84186.0,180000.0,no,no,no,yes
Motor Vehicles & Parts,General Motors,6,2015,Motor Vehicles & Parts,MI,Detroit,60389.0,155929.0,3949.0,177677.0,216000.0,no,yes,no,yes
Retailing,Walmart,1,2015,General Merchandisers,AR,Bentonville,265344.0,485651.0,16363.0,203706.0,2200000.0,no,no,no,yes
Technology,Apple,5,2015,"Computers, Office Equipment",CA,Cupertino,724773.0,182795.0,39510.0,231839.0,97200.0,no,no,no,yes
Telecommunications,AT&T,12,2015,Telecommunications,TX,Dallas,169459.0,132447.0,6224.0,292829.0,243620.0,no,no,no,yes
Transportation,UPS,47,2015,"Mail, Package, and Freight Delivery",GA,Atlanta,87492.0,58232.0,3032.0,35471.0,336150.0,no,no,no,yes
Wholesalers,McKesson,11,2015,Wholesalers: Health Care,CA,San Francisco,52669.0,138030.0,1263.0,51759.0,42800.0,no,no,no,yes

In [36]:
# print last company of every sector
sectors.last()

,name,rank,year,industry,headquarters_state,headquarters_city,market_value_mil,revenue_mil,profit_mil,asset_mil,employees,founder_is_ceo,female_ceo,newcomer_to_fortune_500,global_500
sector,,,,,,,,,,,,,,,
Aerospace & Defense,Huntington Ingalls Industries,375,2023,Aerospace & Defense,VA,Newport News,8265.0,10676.0,579.0,10857.0,43000.0,no,no,no,no
Apparel,Skechers U.S.A.,488,2023,Apparel,CA,Manhattan Beach,7379.0,7445.0,373.0,6894.0,11450.0,yes,no,yes,no
Business Services,Robert Half International,500,2023,Temporary Help,CA,Menlo Park,8677.0,7238.0,658.0,2965.0,16300.0,no,no,no,no
Chemicals,Albemarle,493,2023,Chemicals,NC,Charlotte,25928.0,7320.0,2690.0,15457.0,7400.0,no,no,yes,no
Energy,Par Pacific Holdings,492,2023,Petroleum Refining,TX,Houston,1773.0,7322.0,364.0,3281.0,1397.0,no,no,yes,no
Engineering & Construction,Taylor Morrison Home,457,2023,Homebuilders,AZ,Scottsdale,4144.0,8225.0,1053.0,8471.0,3000.0,no,yes,no,no
Financials,Equinix,497,2023,Real Estate,CA,Redwood City,66873.0,7263.0,704.0,30311.0,12097.0,no,no,no,no
Food & Drug Stores,Rite Aid,161,2023,Food & Drug Stores,PA,Philadelphia,127.0,24568.0,539.0,8529.0,53000.0,no,yes,no,no
"Food, Beverages & Tobacco",Ingredion,468,2023,Food Production,IL,Westchester,6711.0,7946.0,492.0,7561.0,11700.0,no,no,no,no
Health Care,Zoetis,463,2023,Pharmaceuticals,NJ,Parsippany,77053.0,8080.0,2114.0,14925.0,13800.0,no,yes,no,no
"Hotels, Restaurants & Leisure",Chipotle Mexican Grill,438,2023,Food Services,CA,Newport Beach,47186.0,8635.0,899.0,6928.0,104958.0,no,no,no,no
Household Products,Masco,436,2023,"Home Equipment, Furnishings",MI,Livonia,11207.0,8680.0,844.0,5187.0,19000.0,no,no,no,no
Industrials,Rockwell Automation,476,2023,"Electronics, Electrical Equipment",WI,Milwaukee,33683.0,7760.0,932.0,10759.0,26000.0,no,no,no,no
Materials,Sonoco Products,498,2023,"Packaging, Containers",SC,Hartsville,5975.0,7251.0,466.0,7053.0,22000.0,no,no,yes,no
Media,Activision Blizzard,484,2023,Entertainment,CA,Santa Monica,67126.0,7528.0,1513.0,27383.0,13000.0,no,no,no,no
Motor Vehicles & Parts,Autoliv,429,2023,Motor Vehicles & Parts,MI,Auburn Hills,8013.0,8842.0,423.0,7717.0,65300.0,no,no,no,no
Retailing,Bath & Body Works,482,2023,Specialty Retailers: Other,OH,Columbus,8368.0,7560.0,800.0,5494.0,33000.0,no,yes,no,no
Technology,ServiceNow,499,2023,Computer Software,CA,Santa Clara,94338.0,7245.0,325.0,13299.0,20433.0,no,no,yes,no
Telecommunications,Altice USA,397,2023,Telecommunications,NY,Long Island City,1560.0,9648.0,195.0,33665.0,11000.0,no,no,no,no
Transportation,Knight-Swift Transportation Holdings,490,2023,"Trucking, Truck Leasing",AZ,Phoenix,9106.0,7429.0,771.0,10952.0,28300.0,no,no,yes,no
Wholesalers,Watsco,495,2023,Wholesalers: Diversified,FL,Miami,12354.0,7274.0,601.0,3488.0,7238.0,no,no,yes,no

In [40]:
# group method create a dictionay where key is sector/categoricalCol and value is list of index of all particular sector
sectors.groups  # says index no 9466 -> is belong to category Aerospace & Defense 
companys.iloc[9466,:]  # printing row no 9466

name                                    Boeing
rank                                        27
year                                      2015
industry                   Aerospace & Defense
sector                     Aerospace & Defense
headquarters_state                          IL
headquarters_city                      Chicago
market_value_mil                      105032.0
revenue_mil                            90762.0
profit_mil                              5446.0
asset_mil                              99198.0
employees                             165500.0
founder_is_ceo                              no
female_ceo                                  no
newcomer_to_fortune_500                     no
global_500                                 NaN
Name: 9466, dtype: object

In [43]:
# get_group return groups where category = Apparel
sectors.get_group('Apparel')

,name,rank,year,industry,sector,headquarters_state,headquarters_city,market_value_mil,revenue_mil,profit_mil,asset_mil,employees,founder_is_ceo,female_ceo,newcomer_to_fortune_500,global_500
9545,Nike,106,2015,Apparel,Apparel,OR,Beaverton,86679.0,27799.0,2693.0,18594.0,56500.0,no,no,no,NaN
9687,VF,248,2015,Apparel,Apparel,NC,Greensboro,32044.0,12282.0,1048.0,9980.0,59697.0,no,no,no,NaN
9790,PVH,351,2015,Apparel,Apparel,NY,New York,8794.0,8241.0,439.0,10932.0,25850.0,no,no,no,NaN
9813,Ralph Lauren,374,2015,Apparel,Apparel,NY,New York,11482.0,7450.0,776.0,6090.0,18500.0,no,no,no,NaN
9929,Hanesbrands,490,2015,Apparel,Apparel,NC,Winston-Salem,13431.0,5325.0,405.0,5222.0,59500.0,no,no,yes,NaN
10030,Nike,91,2016,Apparel,Apparel,OR,Beaverton,104693.0,30601.0,3273.0,21600.0,62600.0,no,no,no,yes
10170,VF,231,2016,Apparel,Apparel,NC,Greensboro,27422.0,12377.0,1232.0,9640.0,64000.0,no,no,no,no
10279,PVH,340,2016,Apparel,Apparel,NY,New York,8051.0,8020.0,572.0,10696.0,26200.0,no,no,no,no
10293,Ralph Lauren,354,2016,Apparel,Apparel,NY,New York,8087.0,7620.0,702.0,6106.0,20000.0,no,no,no,no
10387,Hanesbrands,448,2016,Apparel,Apparel,NC,Winston-Salem,10997.0,5732.0,429.0,5619.0,65300.0,no,no,no,no
10527,Nike,88,2017,Apparel,Apparel,OR,Beaverton,92204.0,32376.0,3760.0,21396.0,70700.0,no,no,no,yes
10669,VF,230,2017,Apparel,Apparel,NC,Greensboro,22786.0,12207.0,1074.0,9739.0,69000.0,no,no,no,no
10774,PVH,335,2017,Apparel,Apparel,NY,New York,8092.0,8203.0,549.0,11068.0,26650.0,no,no,no,no
10810,Ralph Lauren,371,2017,Apparel,Apparel,NY,New York,6710.0,7405.0,396.0,6213.0,20500.0,no,no,no,no
10871,Hanesbrands,432,2017,Apparel,Apparel,NC,Winston-Salem,7733.0,6063.0,539.0,6908.0,67800.0,no,no,no,no
11028,Nike,89,2018,Apparel,Apparel,OR,Beaverton,108094.0,34350.0,4240.0,23259.0,74400.0,no,no,no,yes
11181,VF,242,2018,Apparel,Apparel,NC,Greensboro,29403.0,12400.0,615.0,9959.0,69000.0,no,no,no,no
11271,PVH,332,2018,Apparel,Apparel,NY,New York,11649.0,8915.0,538.0,11886.0,28050.0,no,no,no,no
11360,Ralph Lauren,421,2018,Apparel,Apparel,NY,New York,9088.0,6653.0,99.0,5652.0,18250.0,no,no,no,no
11372,Hanesbrands,433,2018,Apparel,Apparel,NC,Winston-Salem,6638.0,6478.0,62.0,6895.0,67200.0,no,no,no,no
11529,Nike,90,2019,Apparel,Apparel,OR,Beaverton,132530.0,36397.0,1933.0,22536.0,73100.0,no,no,no,yes
11691,VF,252,2019,Apparel,Apparel,NC,Greensboro,34382.0,12862.0,659.0,10311.0,69000.0,no,no,no,no
11763,PVH,324,2019,Apparel,Apparel,NY,New York,9164.0,9657.0,746.0,11864.0,29350.0,no,no,no,no
11883,Hanesbrands,444,2019,Apparel,Apparel,NC,Winston-Salem,6463.0,6804.0,553.0,7256.0,68000.0,no,no,no,no
11912,Ralph Lauren,473,2019,Apparel,Apparel,NY,New York,10196.0,6182.0,163.0,6143.0,18150.0,no,no,no,no
11923,Tapestry,484,2019,Apparel,Apparel,NY,New York,9421.0,5880.0,398.0,6678.0,16900.0,no,no,yes,no
11939,Levi Strauss,500,2019,Apparel,Apparel,CA,San Francisco,9208.0,5575.0,283.0,3543.0,15100.0,no,no,yes,no
12024,Nike,85,2020,Apparel,Apparel,OR,Beaverton,128857.0,39117.0,4029.0,23717.0,76700.0,no,no,no,yes
12172,VF,233,2020,Apparel,Apparel,CO,Greenwood Village,21347.0,13871.0,1260.0,10357.0,75000.0,no,no,no,no
12262,PVH,322,2020,Apparel,Apparel,NY,New York,2746.0,9909.0,417.0,13631.0,30750.0,no,no,no,no
12375,Hanesbrands,436,2020,Apparel,Apparel,NC,Winston-Salem,2817.0,6967.0,601.0,7354.0,63000.0,no,no,no,no
12408,Ralph Lauren,469,2020,Apparel,Apparel,NY,New York,4928.0,6313.0,431.0,5943.0,18650.0,no,no,no,no
12424,Tapestry,485,2020,Apparel,Apparel,NY,New York,3575.0,6027.0,643.0,6877.0,17400.0,no,yes,no,no
12434,Levi Strauss,495,2020,Apparel,Apparel,CA,San Francisco,4961.0,5763.0,395.0,4232.0,15800.0,no,no,no,no
12524,Nike,85,2021,Apparel,Apparel,OR,Beaverton,209500.0,37403.0,2539.0,31342.0,75400.0,no,no,no,yes
12702,VF,263,2021,Apparel,Apparel,CO,Denver,31306.0,11688.0,679.0,11133.0,48000.0,no,no,no,no
12843,PVH,404,2021,Apparel,Apparel,NY,New York,7523.0,7133.0,1136.0,13294.0,26500.0,no,no,no,no
12871,Hanesbrands,432,2021,Apparel,Apparel,NC,Winston-Salem,6865.0,6664.0,76.0,7699.0,61000.0,no,no,no,no
12889,Ralph Lauren,450,2021,Apparel,Apparel,NY,New York,9005.0,6160.0,384.0,7280.0,19300.0,no,no,no,no
13022,Nike,83,2022,Apparel,Apparel,OR,Beaverton,212779.0,44538.0,5727.0,37740.0,73300.0,no,no,no,yes
13319,VF,380,2022,Apparel,Apparel,CO,Denver,22113.0,9239.0,408.0,13754.0,33600.0,no,no,no,no
13324,PVH,385,2022,Apparel,Apparel,NY,New York,5210.0,9155.0,952.0,12397.0,25000.0,no,no,no,no
13397,Hanesbrands,458,2022,Apparel,Apparel,NC,Winston-Salem,5191.0,7348.0,77.0,7071.0,58000.0,no,no,no,no
13532,Nike,93,2023,Apparel,Apparel,OR,Beaverton,190161.0,46710.0,6046.0,40321.0,79100.0,no,no,no,yes
13788,VF,349,2023,Apparel,Apparel,CO,Denver,8904.0,11842.0,1387.0,13342.0,27650.0,no,no,no,no
13861,PVH,422,2023,Apparel,Apparel,NY,New York,5592.0,9024.0,200.0,11768.0,25000.0,no,no,no,no
13927,Skechers U.S.A.,488,2023,Apparel,Apparel,CA,Manhattan Beach,7379.0,7445.0,373.0,6894.0,11450.0,yes,no,yes,no

In [1]:
# sum(),mean()